package com.bz.dao.pojo.message;

import com.bz.framework.pojo.base.BasePojo;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-10-17 10:45:37
  */
public class MessageRecord extends BasePojo {
    /**
     * 消息数据Id
     * 表字段 : system_message_record.id
     */
    private Integer id;

    /**
     * 消息入库时间
     * 表字段 : system_message_record.createTime
     */
    private Date createtime;

    /**
     * 消息类型
     * 表字段 : system_message_record.type
     */
    private String type;

    /**
     * 消息标题
     * 表字段 : system_message_record.tile
     */
    private String tile;

    /**
     * 消息内容
     * 表字段 : system_message_record.count
     */
    private String count;

    /**
     * 消息文件路径
     * 表字段 : system_message_record.fileIds
     */
    private String fileids;

    /**
     * 电话号码
     * 表字段 : system_message_record.telPhone
     */
    private String telphone;

    /**
     * 短信验证码
     * 表字段 : system_message_record.code
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_message_record
     *
     * @mbg.generated Tue Oct 17 10:45:37 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 消息数据Id 字段:system_message_record.id
     *
     * @return system_message_record.id, 消息数据Id
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 消息数据Id 字段:system_message_record.id
     *
     * @param id the value for system_message_record.id, 消息数据Id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取 消息入库时间 字段:system_message_record.createTime
     *
     * @return system_message_record.createTime, 消息入库时间
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置 消息入库时间 字段:system_message_record.createTime
     *
     * @param createtime the value for system_message_record.createTime, 消息入库时间
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * 获取 消息类型 字段:system_message_record.type
     *
     * @return system_message_record.type, 消息类型
     */
    public String getType() {
        return type;
    }

    /**
     * 设置 消息类型 字段:system_message_record.type
     *
     * @param type the value for system_message_record.type, 消息类型
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * 获取 消息标题 字段:system_message_record.tile
     *
     * @return system_message_record.tile, 消息标题
     */
    public String getTile() {
        return tile;
    }

    /**
     * 设置 消息标题 字段:system_message_record.tile
     *
     * @param tile the value for system_message_record.tile, 消息标题
     */
    public void setTile(String tile) {
        this.tile = tile == null ? null : tile.trim();
    }

    /**
     * 获取 消息内容 字段:system_message_record.count
     *
     * @return system_message_record.count, 消息内容
     */
    public String getCount() {
        return count;
    }

    /**
     * 设置 消息内容 字段:system_message_record.count
     *
     * @param count the value for system_message_record.count, 消息内容
     */
    public void setCount(String count) {
        this.count = count == null ? null : count.trim();
    }

    /**
     * 获取 消息文件路径 字段:system_message_record.fileIds
     *
     * @return system_message_record.fileIds, 消息文件路径
     */
    public String getFileids() {
        return fileids;
    }

    /**
     * 设置 消息文件路径 字段:system_message_record.fileIds
     *
     * @param fileids the value for system_message_record.fileIds, 消息文件路径
     */
    public void setFileids(String fileids) {
        this.fileids = fileids == null ? null : fileids.trim();
    }

    /**
     * 获取 电话号码 字段:system_message_record.telPhone
     *
     * @return system_message_record.telPhone, 电话号码
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * 设置 电话号码 字段:system_message_record.telPhone
     *
     * @param telphone the value for system_message_record.telPhone, 电话号码
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * 获取 短信验证码 字段:system_message_record.code
     *
     * @return system_message_record.code, 短信验证码
     */
    public String getCode() {
        return code;
    }

    /**
     * 设置 短信验证码 字段:system_message_record.code
     *
     * @param code the value for system_message_record.code, 短信验证码
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}