package com.bz.dao.pojo.map;

import com.bz.framework.pojo.base.BasePojo;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-10-24 13:49:38
  */
public class Region extends BasePojo {
    /**
     * 主键
     * 表字段 : system_region.id
     */
    private Integer id;

    /**
     * 
     * 表字段 : system_region.number
     */
    private String number;

    /**
     * 省市区名称
     * 表字段 : system_region.name
     */
    private String name;

    /**
     * 上级ID
     * 表字段 : system_region.parentCode
     */
    private String parentcode;

    /**
     * 级别:0,中国；1，省分；2，市；3，区、县
     * 表字段 : system_region.level
     */
    private Integer level;

    /**
     * 城市代码
     * 表字段 : system_region.citycode
     */
    private String citycode;

    /**
     * 
     * 表字段 : system_region.adcode
     */
    private String adcode;

    /**
     * 经度
     * 表字段 : system_region.lng
     */
    private String lng;

    /**
     * 纬度
     * 表字段 : system_region.lat
     */
    private String lat;

    /**
     * 拼音
     * 表字段 : system_region.pinyin
     */
    private String pinyin;

    /**
     * 
     * 表字段 : system_region.createTime
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_region
     *
     * @mbg.generated Tue Oct 24 13:49:38 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 主键 字段:system_region.id
     *
     * @return system_region.id, 主键
     */
    public Integer getId() {
        return id;
    }

    /**
     * 设置 主键 字段:system_region.id
     *
     * @param id the value for system_region.id, 主键
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取  字段:system_region.number
     *
     * @return system_region.number, 
     */
    public String getNumber() {
        return number;
    }

    /**
     * 设置  字段:system_region.number
     *
     * @param number the value for system_region.number, 
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }

    /**
     * 获取 省市区名称 字段:system_region.name
     *
     * @return system_region.name, 省市区名称
     */
    public String getName() {
        return name;
    }

    /**
     * 设置 省市区名称 字段:system_region.name
     *
     * @param name the value for system_region.name, 省市区名称
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 获取 上级ID 字段:system_region.parentCode
     *
     * @return system_region.parentCode, 上级ID
     */
    public String getParentcode() {
        return parentcode;
    }

    /**
     * 设置 上级ID 字段:system_region.parentCode
     *
     * @param parentcode the value for system_region.parentCode, 上级ID
     */
    public void setParentcode(String parentcode) {
        this.parentcode = parentcode == null ? null : parentcode.trim();
    }

    /**
     * 获取 级别:0,中国；1，省分；2，市；3，区、县 字段:system_region.level
     *
     * @return system_region.level, 级别:0,中国；1，省分；2，市；3，区、县
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * 设置 级别:0,中国；1，省分；2，市；3，区、县 字段:system_region.level
     *
     * @param level the value for system_region.level, 级别:0,中国；1，省分；2，市；3，区、县
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * 获取 城市代码 字段:system_region.citycode
     *
     * @return system_region.citycode, 城市代码
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * 设置 城市代码 字段:system_region.citycode
     *
     * @param citycode the value for system_region.citycode, 城市代码
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * 获取  字段:system_region.adcode
     *
     * @return system_region.adcode, 
     */
    public String getAdcode() {
        return adcode;
    }

    /**
     * 设置  字段:system_region.adcode
     *
     * @param adcode the value for system_region.adcode, 
     */
    public void setAdcode(String adcode) {
        this.adcode = adcode == null ? null : adcode.trim();
    }

    /**
     * 获取 经度 字段:system_region.lng
     *
     * @return system_region.lng, 经度
     */
    public String getLng() {
        return lng;
    }

    /**
     * 设置 经度 字段:system_region.lng
     *
     * @param lng the value for system_region.lng, 经度
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * 获取 纬度 字段:system_region.lat
     *
     * @return system_region.lat, 纬度
     */
    public String getLat() {
        return lat;
    }

    /**
     * 设置 纬度 字段:system_region.lat
     *
     * @param lat the value for system_region.lat, 纬度
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * 获取 拼音 字段:system_region.pinyin
     *
     * @return system_region.pinyin, 拼音
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * 设置 拼音 字段:system_region.pinyin
     *
     * @param pinyin the value for system_region.pinyin, 拼音
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * 获取  字段:system_region.createTime
     *
     * @return system_region.createTime, 
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置  字段:system_region.createTime
     *
     * @param createtime the value for system_region.createTime, 
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}