package com.bz.dao.pojo.upload;

import com.bz.framework.pojo.base.BasePojo;
import java.util.Date;

/**
	* 作者:唐鹏
	* 描述:
	* 版本: version 1.0.0
	* 时间:2017-09-30 16:59:09
  */
public class UploadFileInfo extends BasePojo {
    /**
     * 上传文件Id
     * 表字段 : system_upload_file_info.uploadFileId
     */
    private Long uploadfileid;

    /**
     * 上传文件类型Id
     * 表字段 : system_upload_file_info.uploadTypeId
     */
    private Integer uploadtypeid;

    /**
     * 服务地址
     * 表字段 : system_upload_file_info.serverUrl
     */
    private String serverurl;

    /**
     * 原始文件地址
     * 表字段 : system_upload_file_info.baseFileUrl
     */
    private String basefileurl;

    /**
     * 文件大小(字节)
     * 表字段 : system_upload_file_info.size
     */
    private Long size;

    /**
     * 文件扩展名
     * 表字段 : system_upload_file_info.extName
     */
    private String extname;

    /**
     * 是否删除：0未删除；1已删除
     * 表字段 : system_upload_file_info.isDelete
     */
    private Byte isdelete;

    /**
     * 最后读取时间
     * 表字段 : system_upload_file_info.lastReadTime
     */
    private Integer lastreadtime;

    /**
     * API客户编号
     * 表字段 : system_upload_file_info.apiClientNo
     */
    private String apiclientno;

    /**
     * 创建时间
     * 表字段 : system_upload_file_info.createTime
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table system_upload_file_info
     *
     * @mbg.generated Sat Sep 30 16:59:09 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 上传文件Id 字段:system_upload_file_info.uploadFileId
     *
     * @return system_upload_file_info.uploadFileId, 上传文件Id
     */
    public Long getUploadfileid() {
        return uploadfileid;
    }

    /**
     * 设置 上传文件Id 字段:system_upload_file_info.uploadFileId
     *
     * @param uploadfileid the value for system_upload_file_info.uploadFileId, 上传文件Id
     */
    public void setUploadfileid(Long uploadfileid) {
        this.uploadfileid = uploadfileid;
    }

    /**
     * 获取 上传文件类型Id 字段:system_upload_file_info.uploadTypeId
     *
     * @return system_upload_file_info.uploadTypeId, 上传文件类型Id
     */
    public Integer getUploadtypeid() {
        return uploadtypeid;
    }

    /**
     * 设置 上传文件类型Id 字段:system_upload_file_info.uploadTypeId
     *
     * @param uploadtypeid the value for system_upload_file_info.uploadTypeId, 上传文件类型Id
     */
    public void setUploadtypeid(Integer uploadtypeid) {
        this.uploadtypeid = uploadtypeid;
    }

    /**
     * 获取 服务地址 字段:system_upload_file_info.serverUrl
     *
     * @return system_upload_file_info.serverUrl, 服务地址
     */
    public String getServerurl() {
        return serverurl;
    }

    /**
     * 设置 服务地址 字段:system_upload_file_info.serverUrl
     *
     * @param serverurl the value for system_upload_file_info.serverUrl, 服务地址
     */
    public void setServerurl(String serverurl) {
        this.serverurl = serverurl == null ? null : serverurl.trim();
    }

    /**
     * 获取 原始文件地址 字段:system_upload_file_info.baseFileUrl
     *
     * @return system_upload_file_info.baseFileUrl, 原始文件地址
     */
    public String getBasefileurl() {
        return basefileurl;
    }

    /**
     * 设置 原始文件地址 字段:system_upload_file_info.baseFileUrl
     *
     * @param basefileurl the value for system_upload_file_info.baseFileUrl, 原始文件地址
     */
    public void setBasefileurl(String basefileurl) {
        this.basefileurl = basefileurl == null ? null : basefileurl.trim();
    }

    /**
     * 获取 文件大小(字节) 字段:system_upload_file_info.size
     *
     * @return system_upload_file_info.size, 文件大小(字节)
     */
    public Long getSize() {
        return size;
    }

    /**
     * 设置 文件大小(字节) 字段:system_upload_file_info.size
     *
     * @param size the value for system_upload_file_info.size, 文件大小(字节)
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * 获取 文件扩展名 字段:system_upload_file_info.extName
     *
     * @return system_upload_file_info.extName, 文件扩展名
     */
    public String getExtname() {
        return extname;
    }

    /**
     * 设置 文件扩展名 字段:system_upload_file_info.extName
     *
     * @param extname the value for system_upload_file_info.extName, 文件扩展名
     */
    public void setExtname(String extname) {
        this.extname = extname == null ? null : extname.trim();
    }

    /**
     * 获取 是否删除：0未删除；1已删除 字段:system_upload_file_info.isDelete
     *
     * @return system_upload_file_info.isDelete, 是否删除：0未删除；1已删除
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * 设置 是否删除：0未删除；1已删除 字段:system_upload_file_info.isDelete
     *
     * @param isdelete the value for system_upload_file_info.isDelete, 是否删除：0未删除；1已删除
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * 获取 最后读取时间 字段:system_upload_file_info.lastReadTime
     *
     * @return system_upload_file_info.lastReadTime, 最后读取时间
     */
    public Integer getLastreadtime() {
        return lastreadtime;
    }

    /**
     * 设置 最后读取时间 字段:system_upload_file_info.lastReadTime
     *
     * @param lastreadtime the value for system_upload_file_info.lastReadTime, 最后读取时间
     */
    public void setLastreadtime(Integer lastreadtime) {
        this.lastreadtime = lastreadtime;
    }

    /**
     * 获取 API客户编号 字段:system_upload_file_info.apiClientNo
     *
     * @return system_upload_file_info.apiClientNo, API客户编号
     */
    public String getApiclientno() {
        return apiclientno;
    }

    /**
     * 设置 API客户编号 字段:system_upload_file_info.apiClientNo
     *
     * @param apiclientno the value for system_upload_file_info.apiClientNo, API客户编号
     */
    public void setApiclientno(String apiclientno) {
        this.apiclientno = apiclientno == null ? null : apiclientno.trim();
    }

    /**
     * 获取 创建时间 字段:system_upload_file_info.createTime
     *
     * @return system_upload_file_info.createTime, 创建时间
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * 设置 创建时间 字段:system_upload_file_info.createTime
     *
     * @param createtime the value for system_upload_file_info.createTime, 创建时间
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}